# ===================================================================
# Spring Boot configuration for the "gae" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  port: ${PORT}
management:
  health:
    diskspace:
      enabled: false
jhipster:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        # As this is the PRODUCTION configuration, you MUST change the default key
        # For microservice deployment in GCP this base64-secret must be the same for the Gateway application and all the microservices
        base64-secret: NjA2MzdlMDA2ZjM5NDUwMTc1YmQyZTEzMmY4ZGE3ZmZmYTNlM2M4MmJkMWNhYWY1ZGU0ZDc5NDk3MzBhOGI3ZDVlNWUzZjRkYzhiMjRhMzVlZTYwNWM2ZWNmODYxMjAyNDk5M2U4MWUwNjU5YWU0N2VjNzBmODAxYzRlYmQzODI=
