# ========================================================================
# App Engine Configuration.
# Full reference is available at:
# https://cloud.google.com/appengine/docs/standard/java11/config/appref
# ========================================================================

runtime: java11
instance_class: F1
service: pronounce
handlers:
- url: /(.*)
  script: auto
  secure: always
automatic_scaling:
  min_instances: 1
  max_instances: 2
entrypoint: java -Dthin.root=. -jar pronounce-0.0.1-SNAPSHOT.jar
